

CREATE TABLE apllication_type (
    application_type_id   SMALLINT,
    application_type_name CHARACTER VARYING(200) NOT NULL
);

ALTER TABLE apllication_type ADD CONSTRAINT apllication_type_pk PRIMARY KEY ( application_type_id );

CREATE TABLE application ( 
    application_type_id                  SMALLINT NOT NULL,
    application_id                       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    worker_worker_id                     SMALLINT,
    application_desc                     CHARACTER VARYING(200) NOT NULL
);

ALTER TABLE application ADD CONSTRAINT application_pk PRIMARY KEY ( application_id );

CREATE TABLE application_status (
    application_status_id      SMALLINT NOT NULL,
    application_status_name    CHARACTER VARYING(200) NOT NULL,
    application_application_id INTEGER NOT NULL
);

ALTER TABLE application_status ADD CONSTRAINT application_status_pk PRIMARY KEY ( application_satus_id );



CREATE TABLE hall_rent (
    rent_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rent_start_time  TIME NOT NULL,
    rent_end_time    TIME NOT NULL,
    rent_date        DATE NOT NULL,
    rent_price       NUMBER(10, 2) NOT NULL,
    hall_hall_id     SMALLINT  NOT NULL,
    worker_worker_id SMALLINT  NOT NULL
);

ALTER TABLE hall_rent ADD CONSTRAINT hall_rent_pk PRIMARY KEY ( rent_id );

ALTER TABLE apllication
    ADD CONSTRAINT apllication_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id );

ALTER TABLE application
    ADD CONSTRAINT application_apllication_type_fk FOREIGN KEY ( apllication_type_application_type_id )
        REFERENCES apllication_type ( application_type_id );

ALTER TABLE application_status
    ADD CONSTRAINT application_status_application_fk FOREIGN KEY ( application_application_id )
        REFERENCES application ( application_id );

ALTER TABLE application
    ADD CONSTRAINT application_worker_fk FOREIGN KEY ( worker_worker_id )
        REFERENCES worker ( worker_id );

ALTER TABLE hall_rent
    ADD CONSTRAINT hall_rent_hall_fk FOREIGN KEY ( hall_hall_id )
        REFERENCES hall ( hall_id );

ALTER TABLE hall_rent
    ADD CONSTRAINT hall_rent_worker_fk FOREIGN KEY ( worker_worker_id )
        REFERENCES worker ( worker_id );









-- Generated by Oracle SQL Developer Data Modeler 21.2.0.165.1515
--   at:        2025-01-16 15:38:27 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE



CREATE TABLE application_rent (
    hall_hall_id                             SMALLINT,
    application_rent_id                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    application_rent_date                    date NOT NULL,
    application_rent_start_time              TIME WITHOUT TIME zone NOT NULL,
    application_rent_end_time                TIME WITHOUT TIME zone NOT NULL,
    application_rent_phone                   CHARACTER VARYING(11) NOT NULL,
    application_rent_details                 CHARACTER VARYING(200),
    type_client_type_client_id               SMALLINT NOT NULL, 
);


CREATE TABLE application_status (
    application_status_id   SMALLINT NOT NULL,
    application_status_name CHARACTER VARYING(50) NOT NULL
);

ALTER TABLE application_status ADD CONSTRAINT application_status_pk PRIMARY KEY ( application_status_id );

CREATE TABLE application_type (
    application_type      SMALLINT NOT NULL,
    application_type_name CHARACTER VARYING(50) NOT NULL
);

ALTER TABLE application_type ADD CONSTRAINT application_type_pk PRIMARY KEY ( application_type );


CREATE TABLE application_worker (
    worker_worker_id                     SMALLINT NOT NULL, 
    application_rent_application_rent_id BIGINT NOT NULL,
    application_status_application_status_id SMALLINT NOT NULL
);

ALTER TABLE application_worker ADD CONSTRAINT application_worker_pk PRIMARY KEY ( worker_worker_id,
                                                                                  application_rent_application_rent_id );




CREATE TABLE rent (
    rent_id                              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rent_start_time                      TIME WITHOUT TIME zone NOT NULL,
    rent_end_time                        TIME WITHOUT TIME zone NOT NULL,
    rent_date                            DATE NOT NULL,
    hall_hall_id                         SMALLINT NOT NULL,
    rent_price                           NUMERIC(10, 2)  NOT NULL, 
    application_rent_application_rent_id BIGINT NOT NULL,
    type_client_type_client_id           SMALLINT NOT NULL, 
);

CREATE UNIQUE INDEX rent__idx ON
    rent (
        application_rent_application_rent_id
    ASC );


CREATE TABLE type_client (
    type_client_id   SMALLINT NOT NULL,
    type_client_desc CHARACTER VARYING(50) NOT NULL
);

ALTER TABLE type_client ADD CONSTRAINT type_client_pk PRIMARY KEY ( type_client_id );



ALTER TABLE application_worker
    ADD CONSTRAINT application_rent_application_status_fk FOREIGN KEY ( application_status_application_status_id  )
        REFERENCES application_status ( application_status_id );

ALTER TABLE application_rent
    ADD CONSTRAINT application_rent_application_type_fk FOREIGN KEY (application_type_application_type)
        REFERENCES application_type ( application_type );

ALTER TABLE application_rent
    ADD CONSTRAINT application_rent_hall_fk FOREIGN KEY ( hall_hall_id )
        REFERENCES hall ( hall_id );

ALTER TABLE application_rent
    ADD CONSTRAINT application_rent_type_client_fk FOREIGN KEY ( type_client_type_client_id )
        REFERENCES type_client ( type_client_id );

ALTER TABLE application_worker
    ADD CONSTRAINT application_worker_application_rent_fk FOREIGN KEY ( application_rent_application_rent_id )
        REFERENCES application_rent ( application_rent_id );

ALTER TABLE application_worker
    ADD CONSTRAINT application_worker_worker_fk FOREIGN KEY ( worker_worker_id )
        REFERENCES worker ( worker_id );

ALTER TABLE rent
    ADD CONSTRAINT rent_application_rent_fk FOREIGN KEY ( application_rent_application_rent_id )
        REFERENCES application_rent ( application_rent_id );

ALTER TABLE rent
    ADD CONSTRAINT rent_hall_fk FOREIGN KEY ( hall_hall_id )
        REFERENCES hall ( hall_id );





















